title:             X | N Blog
email:             xinii@msn.com
description:       Welcome!
author:            Xin Li
baseurl:           ""
url:               "https://xinii.github.io"

# Social Profiles
twitter_username:  xintxt
facebook_username: xintxt
github_username:   xinii

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
